server:
  port: 8088
  shutdown: graceful

faaast:
  core:
    request-handler-thread-pool-size: 2
  model:
    path: './samples/demoAAS.json'
    decoupled: true
  endpoint:
    http:
      enabled: true
      port: 8080
    opcua:
      enabled: true
      tcp-port: 8081
      seconds-till-shutdown: 1
  assetconnection:
    opcuaasset:
      enabled: true
      host: 'opc.tcp://jw-Mac.local:53530/OPCUA/SimulationServer'
#    httpasset:
#      enabled: false
#      baseUrl: 'http://localhost'
#    mqttasset:
#      enabled: false
#      serverUri: 'tcp://localhost'
